### PR TITLE
Add curl jsonlite for bing and google

### PR DESCRIPTION
**Pull request by timetheoretical**
I have now implemented the curl and jsonlite solutions for the bing and google APIs, improved the error handling in the async download, and updated the documentation. Let me know if it works for you and if you think anything should be modified.

### CODE REVIEW

**Comment by mhudecheck** [comment]
Merged! : )

**Comment by timetheoretical** [comment]
Great! :) Would you mind testing the three APIs (I have tested them on windows and linux, but it is always useful that someone else try it)?

Also, what would be the next steps for pushing it to CRAN?

**Comment by mhudecheck** [comment]
I'll try to push the changes to CRAN later this week.  I have a couple edits of my own that I want to finish up first (they'll hopefully be done in a couple of days).

**Comment by timetheoretical** [comment]
Okay, sounds good.

**Pull request merged**
